#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: every check the Playwright suite cannot drive, in an order that
# leaves the browser ready for the next one. Nothing here is a secret or a value
# to store, so write_env, set_secret and set_var stay unused.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PORT="${PORT:-8787}"
CHECK_URL="http://localhost:${PORT}/manual-check.html"
SERVER_PID=""

# Every url below is typed into the Chrome that has Spoofer loaded rather than
# handed to open_url, because the operating system's opener cannot promise
# which browser it reaches, and which tab a page lands in is what half of these
# stages are about.

# A stage's verdict. A no is recorded and the run carries on, so one failure
# does not hide the stages after it, and finish lists every one at the end.
verdict() {
  if confirm "$1"; then
    printf '  %s✓ %s%s\n' "$GREEN" "$2" "$RESET"
  else
    SKIPPED+=("FAILED: $2")
    warn "recorded as failed"
  fi
  pause
}

# The check page has to come from a real origin, because an extension cannot
# attach to a file:// page without file access and Spoofer never asks for it.
serve_check_page() {
  node -e '
const http = require("http");
const fs = require("fs");
const path = require("path");
const [dir, port] = process.argv.slice(1);
http
  .createServer((request, response) => {
    const name = path.basename((request.url || "/").split("?")[0]) || "manual-check.html";
    fs.readFile(path.join(dir, name), (error, body) => {
      if (error) {
        response.writeHead(404);
        response.end();
        return;
      }
      response.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      response.end(body);
    });
  })
  .listen(Number(port));
' "$ROOT/scripts" "$PORT" &
  SERVER_PID=$!
  trap 'if [[ -n "$SERVER_PID" ]]; then kill "$SERVER_PID" 2>/dev/null || true; fi' EXIT
}

banner "Spoofer manual checks"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Build Spoofer and load it unpacked"
say "The extension runs out of extension/, so build src/ into it first."
( cd "$ROOT" && npm run build )
say "Serving the check page every later stage uses."
serve_check_page
sleep 1
curl -sf "$CHECK_URL" >/dev/null || warn "the check page is not answering on port $PORT; set PORT and re-run"
note "check page: $CHECK_URL"
say ""
step "In Chrome, open chrome://extensions"
step "Turn Developer mode on, top right."
step "Click 'Load unpacked' and choose this folder: $ROOT/extension"
step "Chrome says the extension changed the page shown on new tabs. Keep Spoofer's page."
step "Click the puzzle-piece icon in the toolbar and pin Spoofer, so its badge is visible."
verdict "Is Spoofer loaded, pinned, and Chrome's new tab page left as Spoofer's?" "loaded unpacked"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pick Tokyo, and watch the debugging bar appear"
say "A fresh install covers nothing and shows no bar until a City is picked."
step "Click the Spoofer icon to open the popup."
step "Type 'tok' in the search box and choose Tokyo."
step "Watch the top of the window: Chrome shows '\"Spoofer\" started debugging this browser'."
note "The bar is one per extension and sits on every tab of every window while Spoofer is attached."
step "Close the popup and read the badge: it should be empty, not OFF and not a red number."
verdict "Is Tokyo selected, the bar showing, and the badge empty?" "Selection and the debugging bar"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The New Tab Page path: a site typed into a fresh tab"
say "This is how most people open a site, and it is the path Spoofer's own New Tab"
say "Page exists to cover: the tab is attached before it goes anywhere."
step "Open a new tab (Cmd-T or Ctrl-T). It should be blank: that is Spoofer's page."
step "Type this url into the omnibox of that same tab and press Enter:"
note "    $CHECK_URL"
step "Read the page: 'Zone the first script saw' should be Asia/Tokyo, offset -540."
note "That line is what a script reading the zone before anything else would have got."
step "'Zone now' should be Asia/Tokyo too, and the clock should show Tokyo time."
verdict "Did the first script see Asia/Tokyo at offset -540?" "New Tab Page first-script zone"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "A third-party check page: zone, coordinates, and the permission prompt"
say "Somebody else's page, so this is not Spoofer marking its own homework."
if confirm "Open a geolocation and time zone check page for you?"; then
  open_url "https://browserleaks.com/geo"
  warn "make sure it opened in the Chrome you loaded Spoofer into, not another browser"
fi
say "Any page that reports both works; browserleaks.com/geo is one."
step "Read the time zone it reports: Asia/Tokyo, UTC+9."
step "Let the page ask for your location. Chrome must raise its own permission prompt,"
step "the same grey bar under the omnibox you would get without Spoofer."
step "Allow it, and check the coordinates land in Tokyo: about 35.7 N, 139.7 E."
note "The point carries a per-install jitter of up to 2 km, so it is near the city, not on it."
step "Open the Spoofer popup and check this tab is counted as covered."
verdict "Zone Tokyo, coordinates in Tokyo, and Chrome's own prompt?" "third-party zone and position"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "A New Tab Page tab that was open before Spoofer covered it"
say "Chrome seals a tab against every extension call while it shows an extension's"
say "New Tab Page, so a tab already sitting there cannot be attached at all. This is"
say "the gap the README names, and it is what a browser start looks like."
step "Open the Spoofer popup and switch Spoofer off."
step "Open a new tab and leave it on the blank page."
step "Open the popup from that tab and switch Spoofer back on."
step "The popup should say one tab is restricted, and the badge should stay empty."
step "Now type $CHECK_URL into that tab."
step "'Zone the first script saw' should be your own zone, not Asia/Tokyo."
step "'Zone now' should be Asia/Tokyo: the tab is reachable again the moment it leaves."
verdict "Restricted while blank, real zone in the first script, Tokyo after?" "sealed New Tab Page tab"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The switch: off and on, with no reload"
step "Keep the check page tab open and watch its clock."
step "Open the popup and switch Spoofer off."
step "The badge reads OFF, and the clock jumps back to your own local time"
step "within a second, without reloading the page."
step "Switch Spoofer back on: the clock returns to Tokyo, still without a reload."
verdict "Did an open tab follow the switch both ways with no reload?" "switch off and on"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The bar's Cancel, and Resume"
say "Dismissing Chrome's debugging bar detaches every tab at once. Spoofer treats"
say "that as the user's decision and never re-attaches on its own."
step "Press Cancel on the '\"Spoofer\" started debugging this browser' bar."
step "The badge reads OFF, and the check page's clock returns to your own zone."
step "Open the popup: it should show a Paused notice with a Resume button."
step "Press Resume: the bar comes back, the badge empties, and the clock returns to Tokyo."
verdict "OFF and Paused after Cancel, covered again after Resume?" "bar Cancel and Resume"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "DevTools, and the DevTools Sensors panel"
say "Opening DevTools must not cost coverage. A time zone set in the Sensors panel"
say "collides with Spoofer's, and whichever side loses, nothing may quietly fall back."
step "Open DevTools on the check page tab (F12 or Cmd-Option-I)."
step "Reload the page and read it: still Asia/Tokyo, and the popup still counts it covered."
step "Now open a new tab, go to $CHECK_URL, and open DevTools on it."
step "In DevTools: the three-dot menu, More tools, Sensors."
step "Under Location, choose a preset in another zone (Tokyo is the one to avoid), or"
step "Manage, then a custom location with a different timezone ID."
step "Read the page's zone and the Spoofer popup together."
note "Either DevTools is refused and the page stays on Tokyo, or DevTools wins and Spoofer"
note "must count that tab as not covered, in red on the badge. What must never happen is a"
note "page on another zone while Spoofer still calls the tab covered."
# Read straight, not through ask: a check outcome is an observation, not a stored value.
printf '  %sWhich happened, in a few words:%s ' "$BOLD" "$RESET"
read -r SENSORS_OUTCOME || true
note "recorded for the commit message: $SENSORS_OUTCOME"
verdict "Did Spoofer and the page agree, whichever side won?" "DevTools and the Sensors panel"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "A service worker restart"
say "An attached session keeps the service worker alive with no timeout, so idling"
say "never exercises this path: the worker has to be stopped by hand."
step "Leave the check page tab open and covered."
step "In another tab, open chrome://serviceworker-internals"
step "Find the registration whose Scope is chrome-extension://<Spoofer's id>/"
step "Press its Stop button."
note "chrome://extensions also has a 'service worker' link that opens its DevTools,"
note "where Application, Service Workers, Stop does the same thing."
step "Go back to the check page: the clock should still show Tokyo, uninterrupted."
step "Open a new tab, go to $CHECK_URL, and check its first script also saw Asia/Tokyo."
step "Open the popup and check both tabs are counted as covered."
verdict "Did open tabs stay covered and a new tab get covered after the restart?" "service worker restart"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Incognito"
step "Open chrome://extensions and click Details on Spoofer."
step "Turn 'Allow in Incognito' on."
step "Open an incognito window (Cmd-Shift-N or Ctrl-Shift-N)."
step "Open a new tab there, then go to $CHECK_URL"
step "The first script should have seen Asia/Tokyo at offset -540, same as a normal window."
step "Check the badge reads the same in both windows, and the popup counts the incognito tab."
verdict "Is an incognito tab covered the same as a normal one?" "incognito"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "A prerendered page, activated by a click"
say "The harness never prerenders at all, with or without Spoofer, so this one is"
say "yours. A prerendered document is covered through its own auto-attached session."
step "Open a new tab and go to $CHECK_URL"
step "Chrome prerenders a second copy of the page in the background."
step "Click 'Follow this link to activate the prerendered copy'."
step "The url should end in ?prerendered and the page should not flash a load."
step "Read 'Zone the first script saw': Asia/Tokyo, offset -540."
note "chrome://predictors and the DevTools Application, Speculative loads panel show"
note "whether Chrome really prerendered it; a page it declined to prerender proves nothing."
verdict "Did the activated prerendered page see Asia/Tokyo in its first script?" "prerender activation"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "A discarded tab, brought back"
say "chrome.tabs.discard closes the harness's connection to the browser, so this one"
say "cannot be driven either."
step "Leave a covered check page tab open, and open chrome://discards in another tab."
step "Find the row for the check page tab in the table."
step "Use its discard action in the Actions column (Urgent Discard does it now)."
step "Switch back to the discarded tab: Chrome reloads it as you look at it."
step "Read 'Zone the first script saw': Asia/Tokyo, offset -540."
step "Open the popup and check the tab is counted as covered again."
verdict "Did the tab come back covered, with Asia/Tokyo in its first script?" "tab discard"

# ── 13 ───────────────────────────────────────────────────────────────────
stage "A browser restart"
say "The city you picked has to outlive a restart. The pause you give Spoofer by"
say "dismissing the bar must not: it lives in session storage, which a restart clears."
step "Press Cancel on the debugging bar, so Spoofer is paused. The badge reads OFF."
step "Quit Chrome completely (Cmd-Q or closing every window)."
step "Start Chrome again and open a new tab, then go to $CHECK_URL"
step "'Zone the first script saw' should be Asia/Tokyo: Spoofer is covering again, so"
step "the pause was forgotten."
step "Open the popup: Tokyo should still be the Selection, with no Paused notice."
verdict "City kept across the restart, pause forgotten?" "browser restart"

finish
note "Sensors panel outcome: ${SENSORS_OUTCOME:-not recorded}"
note "Record today's date, the line above, and every FAILED line in the commit message for this run."
