// Interface: the static City list and the two queries over it.
//   CITIES              -> every City, in catalog order (Asia, Europe, Americas, Africa, Oceania)
//   getCity(id)         -> the City with that id, or undefined
//   searchCities(query) -> every City whose name or country contains the query, case-insensitive,
//                          in catalog order; an empty query matches every City
// Invariants: ids are unique; `zone` is the IANA id Intl reads back unchanged, so the id Spoofer
// sends is the id a page reads. For a handful of zones that is CLDR's older alias (Asia/Calcutta,
// not Asia/Kolkata), which is the id an unmodified Chrome reports for the same system zone.
// latitude is in [-90, 90] and longitude in [-180, 180].
// Pure: no chrome, no I/O, no state, nothing added at runtime. Neither query ever throws.

export type City = {
  id: string;
  name: string;
  country: string;
  zone: string;
  latitude: number;
  longitude: number;
};

export const CITIES: readonly City[] = [
  { id: 'tokyo', name: 'Tokyo', country: 'Japan', zone: 'Asia/Tokyo', latitude: 35.6762, longitude: 139.6503 },
  { id: 'osaka', name: 'Osaka', country: 'Japan', zone: 'Asia/Tokyo', latitude: 34.6937, longitude: 135.5023 },
  { id: 'seoul', name: 'Seoul', country: 'South Korea', zone: 'Asia/Seoul', latitude: 37.5665, longitude: 126.978 },
  { id: 'beijing', name: 'Beijing', country: 'China', zone: 'Asia/Shanghai', latitude: 39.9042, longitude: 116.4074 },
  { id: 'shanghai', name: 'Shanghai', country: 'China', zone: 'Asia/Shanghai', latitude: 31.2304, longitude: 121.4737 },
  { id: 'guangzhou', name: 'Guangzhou', country: 'China', zone: 'Asia/Shanghai', latitude: 23.1291, longitude: 113.2644 },
  { id: 'hong-kong', name: 'Hong Kong', country: 'Hong Kong', zone: 'Asia/Hong_Kong', latitude: 22.3193, longitude: 114.1694 },
  { id: 'taipei', name: 'Taipei', country: 'Taiwan', zone: 'Asia/Taipei', latitude: 25.033, longitude: 121.5654 },
  { id: 'singapore', name: 'Singapore', country: 'Singapore', zone: 'Asia/Singapore', latitude: 1.3521, longitude: 103.8198 },
  { id: 'kuala-lumpur', name: 'Kuala Lumpur', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur', latitude: 3.139, longitude: 101.6869 },
  { id: 'bangkok', name: 'Bangkok', country: 'Thailand', zone: 'Asia/Bangkok', latitude: 13.7563, longitude: 100.5018 },
  { id: 'ho-chi-minh-city', name: 'Ho Chi Minh City', country: 'Vietnam', zone: 'Asia/Saigon', latitude: 10.8231, longitude: 106.6297 },
  { id: 'hanoi', name: 'Hanoi', country: 'Vietnam', zone: 'Asia/Saigon', latitude: 21.0278, longitude: 105.8342 },
  { id: 'jakarta', name: 'Jakarta', country: 'Indonesia', zone: 'Asia/Jakarta', latitude: -6.2088, longitude: 106.8456 },
  { id: 'manila', name: 'Manila', country: 'Philippines', zone: 'Asia/Manila', latitude: 14.5995, longitude: 120.9842 },
  { id: 'yangon', name: 'Yangon', country: 'Myanmar', zone: 'Asia/Rangoon', latitude: 16.8409, longitude: 96.1735 },
  { id: 'dhaka', name: 'Dhaka', country: 'Bangladesh', zone: 'Asia/Dhaka', latitude: 23.8103, longitude: 90.4125 },
  { id: 'mumbai', name: 'Mumbai', country: 'India', zone: 'Asia/Calcutta', latitude: 19.076, longitude: 72.8777 },
  { id: 'delhi', name: 'Delhi', country: 'India', zone: 'Asia/Calcutta', latitude: 28.6139, longitude: 77.209 },
  { id: 'bengaluru', name: 'Bengaluru', country: 'India', zone: 'Asia/Calcutta', latitude: 12.9716, longitude: 77.5946 },
  { id: 'kolkata', name: 'Kolkata', country: 'India', zone: 'Asia/Calcutta', latitude: 22.5726, longitude: 88.3639 },
  { id: 'chennai', name: 'Chennai', country: 'India', zone: 'Asia/Calcutta', latitude: 13.0827, longitude: 80.2707 },
  { id: 'hyderabad', name: 'Hyderabad', country: 'India', zone: 'Asia/Calcutta', latitude: 17.385, longitude: 78.4867 },
  { id: 'kathmandu', name: 'Kathmandu', country: 'Nepal', zone: 'Asia/Katmandu', latitude: 27.7172, longitude: 85.324 },
  { id: 'colombo', name: 'Colombo', country: 'Sri Lanka', zone: 'Asia/Colombo', latitude: 6.9271, longitude: 79.8612 },
  { id: 'karachi', name: 'Karachi', country: 'Pakistan', zone: 'Asia/Karachi', latitude: 24.8607, longitude: 67.0011 },
  { id: 'lahore', name: 'Lahore', country: 'Pakistan', zone: 'Asia/Karachi', latitude: 31.5204, longitude: 74.3587 },
  { id: 'kabul', name: 'Kabul', country: 'Afghanistan', zone: 'Asia/Kabul', latitude: 34.5553, longitude: 69.2075 },
  { id: 'tashkent', name: 'Tashkent', country: 'Uzbekistan', zone: 'Asia/Tashkent', latitude: 41.2995, longitude: 69.2401 },
  { id: 'almaty', name: 'Almaty', country: 'Kazakhstan', zone: 'Asia/Almaty', latitude: 43.222, longitude: 76.8512 },
  { id: 'baku', name: 'Baku', country: 'Azerbaijan', zone: 'Asia/Baku', latitude: 40.4093, longitude: 49.8671 },
  { id: 'tbilisi', name: 'Tbilisi', country: 'Georgia', zone: 'Asia/Tbilisi', latitude: 41.7151, longitude: 44.8271 },
  { id: 'yerevan', name: 'Yerevan', country: 'Armenia', zone: 'Asia/Yerevan', latitude: 40.1792, longitude: 44.4991 },
  { id: 'tehran', name: 'Tehran', country: 'Iran', zone: 'Asia/Tehran', latitude: 35.6892, longitude: 51.389 },
  { id: 'baghdad', name: 'Baghdad', country: 'Iraq', zone: 'Asia/Baghdad', latitude: 33.3152, longitude: 44.3661 },
  { id: 'dubai', name: 'Dubai', country: 'United Arab Emirates', zone: 'Asia/Dubai', latitude: 25.2048, longitude: 55.2708 },
  { id: 'doha', name: 'Doha', country: 'Qatar', zone: 'Asia/Qatar', latitude: 25.2854, longitude: 51.531 },
  { id: 'riyadh', name: 'Riyadh', country: 'Saudi Arabia', zone: 'Asia/Riyadh', latitude: 24.7136, longitude: 46.6753 },
  { id: 'kuwait-city', name: 'Kuwait City', country: 'Kuwait', zone: 'Asia/Kuwait', latitude: 29.3759, longitude: 47.9774 },
  { id: 'muscat', name: 'Muscat', country: 'Oman', zone: 'Asia/Muscat', latitude: 23.588, longitude: 58.3829 },
  { id: 'amman', name: 'Amman', country: 'Jordan', zone: 'Asia/Amman', latitude: 31.9454, longitude: 35.9284 },
  { id: 'beirut', name: 'Beirut', country: 'Lebanon', zone: 'Asia/Beirut', latitude: 33.8938, longitude: 35.5018 },
  { id: 'tel-aviv', name: 'Tel Aviv', country: 'Israel', zone: 'Asia/Jerusalem', latitude: 32.0853, longitude: 34.7818 },
  { id: 'ulaanbaatar', name: 'Ulaanbaatar', country: 'Mongolia', zone: 'Asia/Ulaanbaatar', latitude: 47.8864, longitude: 106.9057 },
  { id: 'london', name: 'London', country: 'United Kingdom', zone: 'Europe/London', latitude: 51.5074, longitude: -0.1278 },
  { id: 'manchester', name: 'Manchester', country: 'United Kingdom', zone: 'Europe/London', latitude: 53.4808, longitude: -2.2426 },
  { id: 'edinburgh', name: 'Edinburgh', country: 'United Kingdom', zone: 'Europe/London', latitude: 55.9533, longitude: -3.1883 },
  { id: 'dublin', name: 'Dublin', country: 'Ireland', zone: 'Europe/Dublin', latitude: 53.3498, longitude: -6.2603 },
  { id: 'paris', name: 'Paris', country: 'France', zone: 'Europe/Paris', latitude: 48.8566, longitude: 2.3522 },
  { id: 'lyon', name: 'Lyon', country: 'France', zone: 'Europe/Paris', latitude: 45.764, longitude: 4.8357 },
  { id: 'marseille', name: 'Marseille', country: 'France', zone: 'Europe/Paris', latitude: 43.2965, longitude: 5.3698 },
  { id: 'madrid', name: 'Madrid', country: 'Spain', zone: 'Europe/Madrid', latitude: 40.4168, longitude: -3.7038 },
  { id: 'barcelona', name: 'Barcelona', country: 'Spain', zone: 'Europe/Madrid', latitude: 41.3874, longitude: 2.1686 },
  { id: 'lisbon', name: 'Lisbon', country: 'Portugal', zone: 'Europe/Lisbon', latitude: 38.7223, longitude: -9.1393 },
  { id: 'porto', name: 'Porto', country: 'Portugal', zone: 'Europe/Lisbon', latitude: 41.1579, longitude: -8.6291 },
  { id: 'rome', name: 'Rome', country: 'Italy', zone: 'Europe/Rome', latitude: 41.9028, longitude: 12.4964 },
  { id: 'milan', name: 'Milan', country: 'Italy', zone: 'Europe/Rome', latitude: 45.4642, longitude: 9.19 },
  { id: 'naples', name: 'Naples', country: 'Italy', zone: 'Europe/Rome', latitude: 40.8518, longitude: 14.2681 },
  { id: 'berlin', name: 'Berlin', country: 'Germany', zone: 'Europe/Berlin', latitude: 52.52, longitude: 13.405 },
  { id: 'munich', name: 'Munich', country: 'Germany', zone: 'Europe/Berlin', latitude: 48.1351, longitude: 11.582 },
  { id: 'hamburg', name: 'Hamburg', country: 'Germany', zone: 'Europe/Berlin', latitude: 53.5511, longitude: 9.9937 },
  { id: 'frankfurt', name: 'Frankfurt', country: 'Germany', zone: 'Europe/Berlin', latitude: 50.1109, longitude: 8.6821 },
  { id: 'amsterdam', name: 'Amsterdam', country: 'Netherlands', zone: 'Europe/Amsterdam', latitude: 52.3676, longitude: 4.9041 },
  { id: 'brussels', name: 'Brussels', country: 'Belgium', zone: 'Europe/Brussels', latitude: 50.8503, longitude: 4.3517 },
  { id: 'luxembourg', name: 'Luxembourg', country: 'Luxembourg', zone: 'Europe/Luxembourg', latitude: 49.6116, longitude: 6.1319 },
  { id: 'zurich', name: 'Zurich', country: 'Switzerland', zone: 'Europe/Zurich', latitude: 47.3769, longitude: 8.5417 },
  { id: 'geneva', name: 'Geneva', country: 'Switzerland', zone: 'Europe/Zurich', latitude: 46.2044, longitude: 6.1432 },
  { id: 'vienna', name: 'Vienna', country: 'Austria', zone: 'Europe/Vienna', latitude: 48.2082, longitude: 16.3738 },
  { id: 'prague', name: 'Prague', country: 'Czechia', zone: 'Europe/Prague', latitude: 50.0755, longitude: 14.4378 },
  { id: 'warsaw', name: 'Warsaw', country: 'Poland', zone: 'Europe/Warsaw', latitude: 52.2297, longitude: 21.0122 },
  { id: 'krakow', name: 'Krakow', country: 'Poland', zone: 'Europe/Warsaw', latitude: 50.0647, longitude: 19.945 },
  { id: 'budapest', name: 'Budapest', country: 'Hungary', zone: 'Europe/Budapest', latitude: 47.4979, longitude: 19.0402 },
  { id: 'bucharest', name: 'Bucharest', country: 'Romania', zone: 'Europe/Bucharest', latitude: 44.4268, longitude: 26.1025 },
  { id: 'sofia', name: 'Sofia', country: 'Bulgaria', zone: 'Europe/Sofia', latitude: 42.6977, longitude: 23.3219 },
  { id: 'athens', name: 'Athens', country: 'Greece', zone: 'Europe/Athens', latitude: 37.9838, longitude: 23.7275 },
  { id: 'istanbul', name: 'Istanbul', country: 'Turkey', zone: 'Europe/Istanbul', latitude: 41.0082, longitude: 28.9784 },
  { id: 'belgrade', name: 'Belgrade', country: 'Serbia', zone: 'Europe/Belgrade', latitude: 44.7866, longitude: 20.4489 },
  { id: 'zagreb', name: 'Zagreb', country: 'Croatia', zone: 'Europe/Zagreb', latitude: 45.815, longitude: 15.9819 },
  { id: 'copenhagen', name: 'Copenhagen', country: 'Denmark', zone: 'Europe/Copenhagen', latitude: 55.6761, longitude: 12.5683 },
  { id: 'stockholm', name: 'Stockholm', country: 'Sweden', zone: 'Europe/Stockholm', latitude: 59.3293, longitude: 18.0686 },
  { id: 'oslo', name: 'Oslo', country: 'Norway', zone: 'Europe/Oslo', latitude: 59.9139, longitude: 10.7522 },
  { id: 'helsinki', name: 'Helsinki', country: 'Finland', zone: 'Europe/Helsinki', latitude: 60.1699, longitude: 24.9384 },
  { id: 'reykjavik', name: 'Reykjavik', country: 'Iceland', zone: 'Atlantic/Reykjavik', latitude: 64.1466, longitude: -21.9426 },
  { id: 'tallinn', name: 'Tallinn', country: 'Estonia', zone: 'Europe/Tallinn', latitude: 59.437, longitude: 24.7536 },
  { id: 'riga', name: 'Riga', country: 'Latvia', zone: 'Europe/Riga', latitude: 56.9496, longitude: 24.1052 },
  { id: 'vilnius', name: 'Vilnius', country: 'Lithuania', zone: 'Europe/Vilnius', latitude: 54.6872, longitude: 25.2797 },
  { id: 'kyiv', name: 'Kyiv', country: 'Ukraine', zone: 'Europe/Kiev', latitude: 50.4501, longitude: 30.5234 },
  { id: 'minsk', name: 'Minsk', country: 'Belarus', zone: 'Europe/Minsk', latitude: 53.9006, longitude: 27.559 },
  { id: 'moscow', name: 'Moscow', country: 'Russia', zone: 'Europe/Moscow', latitude: 55.7558, longitude: 37.6173 },
  { id: 'saint-petersburg', name: 'Saint Petersburg', country: 'Russia', zone: 'Europe/Moscow', latitude: 59.9311, longitude: 30.3609 },
  { id: 'vladivostok', name: 'Vladivostok', country: 'Russia', zone: 'Asia/Vladivostok', latitude: 43.1155, longitude: 131.8855 },
  { id: 'new-york', name: 'New York', country: 'United States', zone: 'America/New_York', latitude: 40.7128, longitude: -74.006 },
  { id: 'boston', name: 'Boston', country: 'United States', zone: 'America/New_York', latitude: 42.3601, longitude: -71.0589 },
  { id: 'washington', name: 'Washington', country: 'United States', zone: 'America/New_York', latitude: 38.9072, longitude: -77.0369 },
  { id: 'atlanta', name: 'Atlanta', country: 'United States', zone: 'America/New_York', latitude: 33.749, longitude: -84.388 },
  { id: 'miami', name: 'Miami', country: 'United States', zone: 'America/New_York', latitude: 25.7617, longitude: -80.1918 },
  { id: 'toronto', name: 'Toronto', country: 'Canada', zone: 'America/Toronto', latitude: 43.6532, longitude: -79.3832 },
  { id: 'montreal', name: 'Montreal', country: 'Canada', zone: 'America/Toronto', latitude: 45.5019, longitude: -73.5674 },
  { id: 'chicago', name: 'Chicago', country: 'United States', zone: 'America/Chicago', latitude: 41.8781, longitude: -87.6298 },
  { id: 'houston', name: 'Houston', country: 'United States', zone: 'America/Chicago', latitude: 29.7604, longitude: -95.3698 },
  { id: 'dallas', name: 'Dallas', country: 'United States', zone: 'America/Chicago', latitude: 32.7767, longitude: -96.797 },
  { id: 'winnipeg', name: 'Winnipeg', country: 'Canada', zone: 'America/Winnipeg', latitude: 49.8951, longitude: -97.1384 },
  { id: 'mexico-city', name: 'Mexico City', country: 'Mexico', zone: 'America/Mexico_City', latitude: 19.4326, longitude: -99.1332 },
  { id: 'guadalajara', name: 'Guadalajara', country: 'Mexico', zone: 'America/Mexico_City', latitude: 20.6597, longitude: -103.3496 },
  { id: 'denver', name: 'Denver', country: 'United States', zone: 'America/Denver', latitude: 39.7392, longitude: -104.9903 },
  { id: 'phoenix', name: 'Phoenix', country: 'United States', zone: 'America/Phoenix', latitude: 33.4484, longitude: -112.074 },
  { id: 'calgary', name: 'Calgary', country: 'Canada', zone: 'America/Edmonton', latitude: 51.0447, longitude: -114.0719 },
  { id: 'los-angeles', name: 'Los Angeles', country: 'United States', zone: 'America/Los_Angeles', latitude: 34.0522, longitude: -118.2437 },
  { id: 'san-francisco', name: 'San Francisco', country: 'United States', zone: 'America/Los_Angeles', latitude: 37.7749, longitude: -122.4194 },
  { id: 'seattle', name: 'Seattle', country: 'United States', zone: 'America/Los_Angeles', latitude: 47.6062, longitude: -122.3321 },
  { id: 'las-vegas', name: 'Las Vegas', country: 'United States', zone: 'America/Los_Angeles', latitude: 36.1699, longitude: -115.1398 },
  { id: 'vancouver', name: 'Vancouver', country: 'Canada', zone: 'America/Vancouver', latitude: 49.2827, longitude: -123.1207 },
  { id: 'anchorage', name: 'Anchorage', country: 'United States', zone: 'America/Anchorage', latitude: 61.2181, longitude: -149.9003 },
  { id: 'honolulu', name: 'Honolulu', country: 'United States', zone: 'Pacific/Honolulu', latitude: 21.3069, longitude: -157.8583 },
  { id: 'panama-city', name: 'Panama City', country: 'Panama', zone: 'America/Panama', latitude: 8.9824, longitude: -79.5199 },
  { id: 'san-jose', name: 'San Jose', country: 'Costa Rica', zone: 'America/Costa_Rica', latitude: 9.9281, longitude: -84.0907 },
  { id: 'havana', name: 'Havana', country: 'Cuba', zone: 'America/Havana', latitude: 23.1136, longitude: -82.3666 },
  { id: 'san-juan', name: 'San Juan', country: 'Puerto Rico', zone: 'America/Puerto_Rico', latitude: 18.4655, longitude: -66.1057 },
  { id: 'bogota', name: 'Bogota', country: 'Colombia', zone: 'America/Bogota', latitude: 4.711, longitude: -74.0721 },
  { id: 'lima', name: 'Lima', country: 'Peru', zone: 'America/Lima', latitude: -12.0464, longitude: -77.0428 },
  { id: 'quito', name: 'Quito', country: 'Ecuador', zone: 'America/Guayaquil', latitude: -0.1807, longitude: -78.4678 },
  { id: 'caracas', name: 'Caracas', country: 'Venezuela', zone: 'America/Caracas', latitude: 10.4806, longitude: -66.9036 },
  { id: 'santiago', name: 'Santiago', country: 'Chile', zone: 'America/Santiago', latitude: -33.4489, longitude: -70.6693 },
  { id: 'buenos-aires', name: 'Buenos Aires', country: 'Argentina', zone: 'America/Buenos_Aires', latitude: -34.6037, longitude: -58.3816 },
  { id: 'montevideo', name: 'Montevideo', country: 'Uruguay', zone: 'America/Montevideo', latitude: -34.9011, longitude: -56.1645 },
  { id: 'asuncion', name: 'Asuncion', country: 'Paraguay', zone: 'America/Asuncion', latitude: -25.2637, longitude: -57.5759 },
  { id: 'la-paz', name: 'La Paz', country: 'Bolivia', zone: 'America/La_Paz', latitude: -16.4897, longitude: -68.1193 },
  { id: 'sao-paulo', name: 'Sao Paulo', country: 'Brazil', zone: 'America/Sao_Paulo', latitude: -23.5505, longitude: -46.6333 },
  { id: 'rio-de-janeiro', name: 'Rio de Janeiro', country: 'Brazil', zone: 'America/Sao_Paulo', latitude: -22.9068, longitude: -43.1729 },
  { id: 'brasilia', name: 'Brasilia', country: 'Brazil', zone: 'America/Sao_Paulo', latitude: -15.7939, longitude: -47.8828 },
  { id: 'manaus', name: 'Manaus', country: 'Brazil', zone: 'America/Manaus', latitude: -3.119, longitude: -60.0217 },
  { id: 'cairo', name: 'Cairo', country: 'Egypt', zone: 'Africa/Cairo', latitude: 30.0444, longitude: 31.2357 },
  { id: 'casablanca', name: 'Casablanca', country: 'Morocco', zone: 'Africa/Casablanca', latitude: 33.5731, longitude: -7.5898 },
  { id: 'algiers', name: 'Algiers', country: 'Algeria', zone: 'Africa/Algiers', latitude: 36.7538, longitude: 3.0588 },
  { id: 'tunis', name: 'Tunis', country: 'Tunisia', zone: 'Africa/Tunis', latitude: 36.8065, longitude: 10.1815 },
  { id: 'tripoli', name: 'Tripoli', country: 'Libya', zone: 'Africa/Tripoli', latitude: 32.8872, longitude: 13.1913 },
  { id: 'lagos', name: 'Lagos', country: 'Nigeria', zone: 'Africa/Lagos', latitude: 6.5244, longitude: 3.3792 },
  { id: 'accra', name: 'Accra', country: 'Ghana', zone: 'Africa/Accra', latitude: 5.6037, longitude: -0.187 },
  { id: 'dakar', name: 'Dakar', country: 'Senegal', zone: 'Africa/Dakar', latitude: 14.7167, longitude: -17.4677 },
  { id: 'abidjan', name: 'Abidjan', country: 'Ivory Coast', zone: 'Africa/Abidjan', latitude: 5.36, longitude: -4.0083 },
  { id: 'nairobi', name: 'Nairobi', country: 'Kenya', zone: 'Africa/Nairobi', latitude: -1.2921, longitude: 36.8219 },
  { id: 'addis-ababa', name: 'Addis Ababa', country: 'Ethiopia', zone: 'Africa/Addis_Ababa', latitude: 9.03, longitude: 38.74 },
  { id: 'dar-es-salaam', name: 'Dar es Salaam', country: 'Tanzania', zone: 'Africa/Dar_es_Salaam', latitude: -6.7924, longitude: 39.2083 },
  { id: 'kampala', name: 'Kampala', country: 'Uganda', zone: 'Africa/Kampala', latitude: 0.3476, longitude: 32.5825 },
  { id: 'kigali', name: 'Kigali', country: 'Rwanda', zone: 'Africa/Kigali', latitude: -1.9441, longitude: 30.0619 },
  { id: 'kinshasa', name: 'Kinshasa', country: 'DR Congo', zone: 'Africa/Kinshasa', latitude: -4.4419, longitude: 15.2663 },
  { id: 'luanda', name: 'Luanda', country: 'Angola', zone: 'Africa/Luanda', latitude: -8.839, longitude: 13.2894 },
  { id: 'harare', name: 'Harare', country: 'Zimbabwe', zone: 'Africa/Harare', latitude: -17.8252, longitude: 31.0335 },
  { id: 'lusaka', name: 'Lusaka', country: 'Zambia', zone: 'Africa/Lusaka', latitude: -15.3875, longitude: 28.3228 },
  { id: 'maputo', name: 'Maputo', country: 'Mozambique', zone: 'Africa/Maputo', latitude: -25.9692, longitude: 32.5732 },
  { id: 'johannesburg', name: 'Johannesburg', country: 'South Africa', zone: 'Africa/Johannesburg', latitude: -26.2041, longitude: 28.0473 },
  { id: 'cape-town', name: 'Cape Town', country: 'South Africa', zone: 'Africa/Johannesburg', latitude: -33.9249, longitude: 18.4241 },
  { id: 'khartoum', name: 'Khartoum', country: 'Sudan', zone: 'Africa/Khartoum', latitude: 15.5007, longitude: 32.5599 },
  { id: 'sydney', name: 'Sydney', country: 'Australia', zone: 'Australia/Sydney', latitude: -33.8688, longitude: 151.2093 },
  { id: 'melbourne', name: 'Melbourne', country: 'Australia', zone: 'Australia/Melbourne', latitude: -37.8136, longitude: 144.9631 },
  { id: 'brisbane', name: 'Brisbane', country: 'Australia', zone: 'Australia/Brisbane', latitude: -27.4698, longitude: 153.0251 },
  { id: 'perth', name: 'Perth', country: 'Australia', zone: 'Australia/Perth', latitude: -31.9505, longitude: 115.8605 },
  { id: 'adelaide', name: 'Adelaide', country: 'Australia', zone: 'Australia/Adelaide', latitude: -34.9285, longitude: 138.6007 },
  { id: 'hobart', name: 'Hobart', country: 'Australia', zone: 'Australia/Hobart', latitude: -42.8821, longitude: 147.3272 },
  { id: 'darwin', name: 'Darwin', country: 'Australia', zone: 'Australia/Darwin', latitude: -12.4634, longitude: 130.8456 },
  { id: 'auckland', name: 'Auckland', country: 'New Zealand', zone: 'Pacific/Auckland', latitude: -36.8485, longitude: 174.7633 },
  { id: 'wellington', name: 'Wellington', country: 'New Zealand', zone: 'Pacific/Auckland', latitude: -41.2865, longitude: 174.7762 },
  { id: 'suva', name: 'Suva', country: 'Fiji', zone: 'Pacific/Fiji', latitude: -18.1416, longitude: 178.4419 },
];

export function getCity(id: string): City | undefined {
  return CITIES.find((city) => city.id === id);
}

export function searchCities(query: string): City[] {
  const needle = query.trim().toLowerCase();
  return CITIES.filter((city) => `${city.name} ${city.country}`.toLowerCase().includes(needle));
}
